version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - app
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colaborae
    restart: unless-stopped
  # APP*****************************************
  colaborae:
    build: ./
    container_name: colaborae
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - app
    #restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_DB=postgres

volumes:
  postgres-data:
networks:
  app:
